name: ws_server
description: >
  A web server that uses web sockets to communicate with clients.
version: 0.0.1
homepage: https://github.com/plugfox/ws
repository: https://github.com/plugfox/ws
issue_tracker: https://github.com/plugfox/ws/issues
publish_to: 'none'

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  # HTTP Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

  # Logger
  l: ^4.1.0-pre.1

  # Utilities
  args: ^2.4.2
  meta: ^1.9.1
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
